version: '3'
services:
        postgres:
                build: postgres/
                container_name: ${PG_CONTAINER_NAME}
                environment:
                        POSTGRES_DB: ${POSTGRES_DB}
                        POSTGRES_USER: ${POSTGRES_USER}
                        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
                        PGDATA: ${PGDATA}
                volumes:
                        - postgres:/var/lib/pgsql
                ports:
                        - ${PG_PORT}
                restart: unless-stopped
        pgadmin4:
               build: pgadmin4/
               container_name: ${PGADMIN_CONTAINER_NAME}
               environment:
                       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
                       PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
               ports:
                       - ${PGADMIN_PORT}
               restart: unless-stopped
        grafana:
                container_name: ${GRAFANA_CONTAINER_NAME}
                image: grafana/grafana:latest
                ports:
                        - ${GRAFANA_PORT}
                environment:
                        - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
                volumes:
                        - grafana:/var/lib/grafana

        pushgateway:
                container_name: ${PUSHGATEWAY_CONTAINER_NAME}
                image: prom/pushgateway:latest
                ports:
                        - ${PUSHGATEWAY_PORT}
                command: ["--web.listen-address=:9090"]

        node_exporter:
                container_name: ${NODE_CONTAINER_NAME}
                image: prom/node-exporter:latest
                ports:
                        - ${NODE_PORT}
                command: ["--collector.textfile.directory=/etc/node-exporter/textfile_collector"]
                volumes:
                        - ./node-exporter:/etc/node-exporter/textfile_collector
        prometheus:
                image: prom/prometheus:latest
                container_name: ${PROMETHEUS_CONTAINER_NAME}
                ports: 
                        - ${PROMETHEUS_PORT}
                volumes:
                        - prometheus:/etc/prometheus/
                command:
                        - --config.file=/etc/prometheus/prometheus.yml
        ihm-omega:
               build: /home/ec2-user/omega/ihm-omega/
               container_name: ${IHM_OMEGA_CONTAINER_NAME}
               ports:
                       - ${IHM_OMEGA_PORT}
               restart: unless-stopped

volumes:
        postgres:
                driver: local
                driver_opts:
                        type: 'none'
                        o: 'bind'
                        device: /data/volumes/postgres

        grafana:
                driver: local
                driver_opts:
                        type: 'none'
                        o: 'bind'
                        device: /data/volumes/grafana
        prometheus:
                driver: local
                driver_opts:
                        type: 'none'
                        o: 'bind'
                        device: /data/volumes/prometheus
